### ISSUE TITLE
Include parts list?

### ISSUE THREAD

**Issue by x46085** [willem-pennings/balancing-cube#1]
Hello!

I've set about trying to build this, and ordered all the parts listed in the Article and Readme / in repo. 

I've ordered:
- motors
- motor controllers

I'm currently missing:
- the exact countersunk screws & count
- the capacitors by type and count
- the other transistors / parts seen on the PCBs
- the exact small radial ball bearing used
- the exact battery used (useful for dimensions even if I get a different one)

A picture of the PCB without the controllers and ESP32 in place would be helpful, especially to see the IMU placement and make sure I have it correct. 

Thank you for creating this project! It's enjoyable and inspiring to build.

**Comment by willem-pennings** [comment]
I suppose you haven't found the BOM yet. It is available in the repository. I did notice that I forgot to add the ball bearings. I have added them now. You can inspect the PCB using KiCad.

**Comment by x46085** [comment]
Awesome, thanks!
