### ISSUE TITLE
Batteryboard design

### ISSUE THREAD

**Issue by Manny7115** [willem-pennings/balancing-cube#3]
The schematic for the battery board has pin 1 on the OUT connector floating, I believe this is an error and they should be tied together to pin 1 of the IN connector.

Also based on the switch position the power flows opposite of the indicated ON or OFF labels. I have switched the labels and added pin 1 on the OUT connector to the GND plane on my own board.

**Comment by willem-pennings** [comment]
Thank you for the remark. You are completely right! I must have messed this up between ordering the boards and adding them to this repository, because my boards do not have this issue. I have fixed the mistake now.
